2021-05-18 09:53:19,913 INFO    MainThread:96109 [wandb_setup.py:_flush():69] setting env: {}
2021-05-18 09:53:19,913 INFO    MainThread:96109 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-18 09:53:19,913 INFO    MainThread:96109 [wandb_init.py:_log_setup():336] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/American-Sign-Language-Recognition/wandb/run-20210518_095319-2ulg894d/logs/debug.log
2021-05-18 09:53:19,913 INFO    MainThread:96109 [wandb_init.py:_log_setup():337] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/American-Sign-Language-Recognition/wandb/run-20210518_095319-2ulg894d/logs/debug-internal.log
2021-05-18 09:53:19,914 INFO    MainThread:96109 [wandb_init.py:_jupyter_setup():287] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f264aed96a0>
2021-05-18 09:53:19,914 INFO    MainThread:96109 [wandb_init.py:init():369] calling init triggers
2021-05-18 09:53:19,914 INFO    MainThread:96109 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-18 09:53:19,914 INFO    MainThread:96109 [wandb_init.py:init():391] re-initializing run, found existing run on stack: q38hqubh
2021-05-18 09:53:19,915 INFO    MainThread:96109 [wandb_run.py:finish():1208] finishing run ranuga-d/Sign-Language-Recognition/q38hqubh
2021-05-18 09:53:19,915 INFO    MainThread:96109 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 0
2021-05-18 09:53:19,915 INFO    MainThread:96109 [wandb_run.py:_restore():1507] restore
2021-05-18 09:53:19,918 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 724
  total_bytes: 724
}

2021-05-18 09:53:22,102 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 724
  total_bytes: 724
}

2021-05-18 09:53:22,816 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 724
  total_bytes: 11827
}

2021-05-18 09:53:23,199 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 724
  total_bytes: 17540
}

2021-05-18 09:53:23,302 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 724
  total_bytes: 17540
}

2021-05-18 09:53:23,404 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 724
  total_bytes: 17540
}

2021-05-18 09:53:23,506 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 724
  total_bytes: 17540
}

2021-05-18 09:53:23,607 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 724
  total_bytes: 17540
}

2021-05-18 09:53:23,709 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11790
  total_bytes: 17540
}

2021-05-18 09:53:23,811 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17540
  total_bytes: 17540
}

2021-05-18 09:53:23,914 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17540
  total_bytes: 17540
}

2021-05-18 09:53:24,016 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17540
  total_bytes: 17540
}

2021-05-18 09:53:24,118 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17540
  total_bytes: 17540
}

2021-05-18 09:53:24,219 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17540
  total_bytes: 17540
}

2021-05-18 09:53:24,321 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17540
  total_bytes: 17540
}

2021-05-18 09:53:24,422 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17540
  total_bytes: 17540
}

2021-05-18 09:53:24,524 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17540
  total_bytes: 17540
}

2021-05-18 09:53:25,815 INFO    MainThread:96109 [wandb_run.py:_show_files():1879] logging synced files
2021-05-18 09:53:25,818 INFO    MainThread:96109 [wandb_init.py:init():418] starting backend
2021-05-18 09:53:25,818 INFO    MainThread:96109 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-18 09:53:25,821 INFO    MainThread:96109 [backend.py:ensure_launched():132] starting backend process...
2021-05-18 09:53:25,854 INFO    MainThread:96109 [backend.py:ensure_launched():137] started backend process with pid: 102632
2021-05-18 09:53:25,855 INFO    MainThread:96109 [wandb_init.py:init():423] backend started and connected
2021-05-18 09:53:25,867 INFO    MainThread:96109 [wandb_init.py:init():465] updated telemetry
2021-05-18 09:53:25,867 INFO    MainThread:96109 [wandb_init.py:init():484] communicating current version
2021-05-18 09:53:26,696 INFO    MainThread:96109 [wandb_init.py:init():489] got version response 
2021-05-18 09:53:26,696 INFO    MainThread:96109 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-18 09:53:27,491 INFO    MainThread:96109 [wandb_init.py:init():522] starting run threads in backend
2021-05-18 09:53:32,496 INFO    MainThread:96109 [wandb_run.py:_console_start():1565] atexit reg
2021-05-18 09:53:32,497 INFO    MainThread:96109 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.WRAP
2021-05-18 09:53:32,497 INFO    MainThread:96109 [wandb_run.py:_redirect():1455] Wrapping output streams.
2021-05-18 09:53:32,497 INFO    MainThread:96109 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-18 09:53:32,497 INFO    MainThread:96109 [wandb_init.py:init():546] run started, returning control to user process
2021-05-18 09:53:34,169 INFO    MainThread:96109 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-18 09:53:34,170 INFO    MainThread:96109 [jupyter.py:save_ipynb():268] looking for notebook: main.ipynb
2021-05-18 09:53:34,837 INFO    MainThread:96109 [wandb_init.py:_pause_backend():253] saved code: <wandb.sdk.wandb_artifacts.Artifact object at 0x7f2649941438>
2021-05-18 09:53:38,970 INFO    MainThread:96109 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 0
2021-05-18 09:53:38,971 INFO    MainThread:96109 [wandb_run.py:_restore():1507] restore
2021-05-18 09:53:41,334 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
  artifact_count: 1
}
pusher_stats {
  uploaded_bytes: 29844
  total_bytes: 29844
}

2021-05-18 09:53:42,121 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
  artifact_count: 1
}
pusher_stats {
  uploaded_bytes: 29844
  total_bytes: 29844
}

2021-05-18 09:53:42,516 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
  artifact_count: 1
}
pusher_stats {
  uploaded_bytes: 29844
  total_bytes: 46641
}

